export const AVAILABLE_COLORS = [
  "Pitch black",
  "Pure white",
  "Lemon yellow",
  "Mauve purple",
  "Nuclear red",
  "Outrageous orange",
  "Atomic pink",
  "Royal blue",
  "Light grey",
  "Light blue",
  "Grass green",
  "Beige brown",
  "Teal blue",
  "Army green",
  "Dark grey",
  "Ivory white",
  "Rust copper",
  "Appricot",
  "Lagoon blue",
  "Forest green",
  "Fluorescent orange",
  "Fluorescent green",
  "Transparent",
  "Bhama yellow",
  "Chocolate brown",
  "Fluorescent yellow",
  "Levender violet",
  "Magenta",
  "Military khaki",
  "Ryobix green",
  "Simply silver",
  "Midnight grey",
  "Thanos purple",
  "Cool( lithopane ) white",
];
